# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  ga_coprocessor.v
vsim  -onfinish exit -pli /u/koushik/miniforge3/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.ga_coprocessor 
onbreak resume
run -all
quit
